# #DOGUSOTO FINAL_SALES_FILE AND MASK_SERVIS_BAKIM DATASI (3)

In [19]:
import numpy as np
import pandas as pd

sales = pd.read_csv('../datasets/FINAL_SALES_FILE_DATATHON.csv')
servis_bakim = pd.read_csv('../datasets/MASK_SERVIS_BAKIM_DATATHON_FINAL.csv')

# 5-) FINAL_SALES_FILE_DATATHON

## Genel Bilgiler

In [20]:
sales

Unnamed: 0  CUSTOMER_ID  SALESFILE_ID       SF_CREATE_DATE  STATUS  \
0                0      1712792     7274467.0  2017-11-17 12:15:39     101   
1                1      1149729     4839430.0  2015-11-11 17:03:28     102   
2                2      1697993     4847398.0  2015-11-14 11:15:51     102   
3                3      1680258     3817349.0  2014-12-23 17:26:09     105   
4                4      1244973     8079074.0  2018-08-28 12:55:04     101   
...            ...          ...           ...                  ...     ...   
397521      397521      1151001     3504117.0  2014-09-17 12:30:13     102   
397522      397522      1581191     3518578.0  2014-09-22 20:14:38     105   
397523      397523      1535801     3526258.0  2014-09-25 12:01:58     102   
397524      397524      1205995     6592609.0  2017-04-14 15:40:44     105   
397525      397525      1501605     6614631.0  2017-04-22 11:42:48     102   

       REQ_BRAND_CODE  REQ_TOPMODEL_CODE  
0                   Y             9231.0  
1                   K             9184.0  
2                   Y             9231.0  
3                   Y             9362.0  
4                   K             9901.0  
...               ...                ...  
397521              K             9435.0  
397522              K             9176.0  
397523              T             9352.0  
397524              X             9523.0  
397525              K             9898.0  

[397526 rows x 7 columns]

In [21]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397526 entries, 0 to 397525
Data columns (total 7 columns):
Unnamed: 0           397526 non-null int64
CUSTOMER_ID          397526 non-null int64
SALESFILE_ID         397526 non-null float64
SF_CREATE_DATE       397526 non-null object
STATUS               397526 non-null int64
REQ_BRAND_CODE       397526 non-null object
REQ_TOPMODEL_CODE    397237 non-null float64
dtypes: float64(2), int64(3), object(2)
memory usage: 21.2+ MB


In [53]:
sales.isnull().sum()

Unnamed: 0           0
CUSTOMER_ID          0
SALESFILE_ID         0
SF_CREATE_DATE       0
STATUS               0
REQ_BRAND_CODE       0
REQ_TOPMODEL_CODE    0
dtype: int64

In [52]:
sales = sales.fillna(method='bfill')

In [23]:
sales.duplicated('STATUS').sum()

397520

## Eşsizlik

In [25]:
pd.unique(sales['STATUS'])

array([101, 102, 105, 100, 109, 106], dtype=int64)

In [26]:
pd.unique(sales['REQ_BRAND_CODE'])

array(['Y', 'K', 'Z', 'T', 'X'], dtype=object)

In [54]:
sales['REQ_TOPMODEL_CODE']  = sales.REQ_TOPMODEL_CODE.astype(str).str[:2].astype(int)

In [56]:
pd.unique(sales['REQ_TOPMODEL_CODE'])

array([92, 91, 93, 99, 94, 96, 98, 95, 90, 97], dtype=int64)

In [41]:
pd.unique(sales['REQ_TOPMODEL_CODE'])

array([9231., 9184., 9362., 9901., 9245., 9419., 9352., 9176., 9612.,
       9821., 9511., 9094., 9377., 9390., 9596., 9387., 9524., 9346.,
       9095., 9355., 9936., 9123., 9186., 9527., 9766., 9625., 9817.,
       9522., 9935., 9161., 9640., 9927., 9349., 9526., 9819., 9435.,
       9525., 9692., 9172., 9816., 9351., 9119., 9222., 9298., 9520.,
       9503., 9311., 9235., 9822., 9820., 9201., 9357., 9345., 9430.,
       9374., 9174., 9721., 9605., 9515., 9523., 9581., 9818., 9604.,
       9930., 9763., 9241., 9516., 9200., 9531., 9199., 9438., 9517.,
       9929., 9295., 9359., 9898., 9940., 9767., 9764., 9815., 9931.,
       9431., 9518., 9739., 9281., 9928., 9967., 9969., 9968., 9233.,
       9897., 9434., 9204., 9765., 9358., 9902., 9301., 9626., 9694.,
       9361., 9183., 9509., 9354., 9464., 9336., 9899., 9313., 9823.,
       9907., 9521., 9510., 9240., 9243., 9232., 9533., 9505., 9512.,
       9616., 9312., 9495., 9133., 9083.,   nan, 9645., 9690., 9376.,
       9135., 9163.,

In [59]:
sales['SF_CREATE_DATE']  = sales.SF_CREATE_DATE.astype(str).str[:4].astype(int)

In [61]:
pd.unique(sales['SF_CREATE_DATE'])

array([2017, 2015, 2014, 2018, 2020, 2011, 2013, 2016, 2010, 2019, 2021,
       2012], dtype=int64)

In [30]:
pd.unique(sales['SALESFILE_ID'])

array([7274467., 4839430., 4847398., ..., 3526258., 6592609., 6614631.])

In [31]:
pd.unique(sales['CUSTOMER_ID'])

array([1712792, 1149729, 1697993, ..., 1383901, 1498539, 1649602],
      dtype=int64)

## Values

In [33]:
sales['STATUS'].value_counts(dropna=True)

105    143134
102    142428
101    105773
109      4825
100      1281
106        85
Name: STATUS, dtype: int64

In [32]:
sales['REQ_BRAND_CODE'].value_counts(dropna=True)

Y    143047
K     99840
X     74527
Z     45490
T     34622
Name: REQ_BRAND_CODE, dtype: int64

In [34]:
sales['REQ_TOPMODEL_CODE'].value_counts(dropna=True)

9161.0    19558
9231.0    19107
9901.0    15798
9355.0    15178
9352.0    14478
          ...  
9500.0        1
9444.0        1
9609.0        1
9762.0        1
9451.0        1
Name: REQ_TOPMODEL_CODE, Length: 277, dtype: int64

In [35]:
sales['CUSTOMER_ID'].value_counts(dropna=True)

1192313    286
1047601    266
1136791    264
1379169    262
1441256    242
          ... 
1063290      1
1800847      1
1798798      1
1036679      1
1520000      1
Name: CUSTOMER_ID, Length: 183523, dtype: int64

## Column Categorization

- STATUS

In [36]:
sales['STATUS'] = sales['STATUS'].astype('str')
cleanup_nums_status = {"STATUS":     {"100": 0, "101": 1, "102": 2, "105": 3, "106": 4, "109": 5}}
sales = sales.replace(cleanup_nums_status)

In [37]:
sales

Unnamed: 0  CUSTOMER_ID  SALESFILE_ID       SF_CREATE_DATE  STATUS  \
0                0      1712792     7274467.0  2017-11-17 12:15:39       1   
1                1      1149729     4839430.0  2015-11-11 17:03:28       2   
2                2      1697993     4847398.0  2015-11-14 11:15:51       2   
3                3      1680258     3817349.0  2014-12-23 17:26:09       3   
4                4      1244973     8079074.0  2018-08-28 12:55:04       1   
...            ...          ...           ...                  ...     ...   
397521      397521      1151001     3504117.0  2014-09-17 12:30:13       2   
397522      397522      1581191     3518578.0  2014-09-22 20:14:38       3   
397523      397523      1535801     3526258.0  2014-09-25 12:01:58       2   
397524      397524      1205995     6592609.0  2017-04-14 15:40:44       3   
397525      397525      1501605     6614631.0  2017-04-22 11:42:48       2   

       REQ_BRAND_CODE  REQ_TOPMODEL_CODE  
0                   Y             9231.0  
1                   K             9184.0  
2                   Y             9231.0  
3                   Y             9362.0  
4                   K             9901.0  
...               ...                ...  
397521              K             9435.0  
397522              K             9176.0  
397523              T             9352.0  
397524              X             9523.0  
397525              K             9898.0  

[397526 rows x 7 columns]

- REQ_BRAND_CODE

In [38]:
sales['REQ_BRAND_CODE'] = sales['REQ_BRAND_CODE'].astype('str')
cleanup_nums_code = {"REQ_BRAND_CODE":     {"Y": 0, "K": 1, "Z": 2, "T": 3, "X": 4}}
sales = sales.replace(cleanup_nums_code)

In [39]:
sales

Unnamed: 0  CUSTOMER_ID  SALESFILE_ID       SF_CREATE_DATE  STATUS  \
0                0      1712792     7274467.0  2017-11-17 12:15:39       1   
1                1      1149729     4839430.0  2015-11-11 17:03:28       2   
2                2      1697993     4847398.0  2015-11-14 11:15:51       2   
3                3      1680258     3817349.0  2014-12-23 17:26:09       3   
4                4      1244973     8079074.0  2018-08-28 12:55:04       1   
...            ...          ...           ...                  ...     ...   
397521      397521      1151001     3504117.0  2014-09-17 12:30:13       2   
397522      397522      1581191     3518578.0  2014-09-22 20:14:38       3   
397523      397523      1535801     3526258.0  2014-09-25 12:01:58       2   
397524      397524      1205995     6592609.0  2017-04-14 15:40:44       3   
397525      397525      1501605     6614631.0  2017-04-22 11:42:48       2   

        REQ_BRAND_CODE  REQ_TOPMODEL_CODE  
0                    0             9231.0  
1                    1             9184.0  
2                    0             9231.0  
3                    0             9362.0  
4                    1             9901.0  
...                ...                ...  
397521               1             9435.0  
397522               1             9176.0  
397523               3             9352.0  
397524               4             9523.0  
397525               1             9898.0  

[397526 rows x 7 columns]

In [ ]:
sales['STATUS'] = sales['STATUS'].astype('str')
cleanup_nums_status = {"STATUS":     {"100": 0, "101": 1, "102": 2, "105": 3, "106": 4, "109": 5}}
sales = sales.replace(cleanup_nums_status)

- REQ_TOPMODEL_CODE

In [57]:
sales['REQ_TOPMODEL_CODE'] = sales['REQ_TOPMODEL_CODE'].astype('str')
cleanup_nums_topmodel = {"REQ_TOPMODEL_CODE":     {"90": 0, "91": 1, "92": 2, "93": 3, "94": 4, "95": 5,
                                                 "96": 6, "97": 7, "98": 8, "99": 9}}
sales = sales.replace(cleanup_nums_topmodel)

In [58]:
sales

Unnamed: 0  CUSTOMER_ID  SALESFILE_ID       SF_CREATE_DATE  STATUS  \
0                0      1712792     7274467.0  2017-11-17 12:15:39       1   
1                1      1149729     4839430.0  2015-11-11 17:03:28       2   
2                2      1697993     4847398.0  2015-11-14 11:15:51       2   
3                3      1680258     3817349.0  2014-12-23 17:26:09       3   
4                4      1244973     8079074.0  2018-08-28 12:55:04       1   
...            ...          ...           ...                  ...     ...   
397521      397521      1151001     3504117.0  2014-09-17 12:30:13       2   
397522      397522      1581191     3518578.0  2014-09-22 20:14:38       3   
397523      397523      1535801     3526258.0  2014-09-25 12:01:58       2   
397524      397524      1205995     6592609.0  2017-04-14 15:40:44       3   
397525      397525      1501605     6614631.0  2017-04-22 11:42:48       2   

        REQ_BRAND_CODE  REQ_TOPMODEL_CODE  
0                    0                  2  
1                    1                  1  
2                    0                  2  
3                    0                  3  
4                    1                  9  
...                ...                ...  
397521               1                  4  
397522               1                  1  
397523               3                  3  
397524               4                  5  
397525               1                  8  

[397526 rows x 7 columns]

- SF_CREATE_DATE

In [62]:
sales['SF_CREATE_DATE'] = sales['SF_CREATE_DATE'].astype('str')
cleanup_nums_date = {"SF_CREATE_DATE":     {"2010": 0, "2011": 1, "2012": 2, "2013": 3, "2014": 4, "2015": 5,
                                                 "2016": 6, "2017": 7, "2018": 8, "2019": 9, "2020": 10, "2021": 11}}
sales = sales.replace(cleanup_nums_date)

In [63]:
sales

Unnamed: 0  CUSTOMER_ID  SALESFILE_ID  SF_CREATE_DATE  STATUS  \
0                0      1712792     7274467.0               7       1   
1                1      1149729     4839430.0               5       2   
2                2      1697993     4847398.0               5       2   
3                3      1680258     3817349.0               4       3   
4                4      1244973     8079074.0               8       1   
...            ...          ...           ...             ...     ...   
397521      397521      1151001     3504117.0               4       2   
397522      397522      1581191     3518578.0               4       3   
397523      397523      1535801     3526258.0               4       2   
397524      397524      1205995     6592609.0               7       3   
397525      397525      1501605     6614631.0               7       2   

        REQ_BRAND_CODE  REQ_TOPMODEL_CODE  
0                    0                  2  
1                    1                  1  
2                    0                  2  
3                    0                  3  
4                    1                  9  
...                ...                ...  
397521               1                  4  
397522               1                  1  
397523               3                  3  
397524               4                  5  
397525               1                  8  

[397526 rows x 7 columns]

In [89]:
sales.to_csv("sales.csv", index=False)

# 6-) MASK_SERVIS_BAKIM_DATATHON_FINAL

## Genel Bilgiler 

In [64]:
# IS_MAINTENANCE ==> BAKIM = 1, SERVİS = 0
servis_bakim

Unnamed: 0          CREATE_DATE  IS_MAINTENANCE  VEHICLE_ID  \
0                 0  2010-12-29 10:50:56               1     5000001   
1                 1  2013-08-21 10:34:21               1     5000001   
2                 2  2015-11-30 10:55:00               1     5000001   
3                 3  2015-12-09 13:38:49               0     5000001   
4                 4  2017-11-23 09:53:22               1     5000001   
...             ...                  ...             ...         ...   
1040995     1040995  2021-05-20 14:58:31               0     5344976   
1040996     1040996  2021-05-24 09:57:34               0     5344981   
1040997     1040997  2021-05-25 12:44:02               0     5344999   
1040998     1040998  2021-05-27 09:45:00               0     5345037   
1040999     1040999  2021-05-28 13:46:36               0     5345048   

         TOTAL_AMOUNT_TL  
0                  192.0  
1                  267.0  
2                 1747.0  
3                  465.0  
4                  549.0  
...                  ...  
1040995           1180.0  
1040996              0.0  
1040997           3258.0  
1040998              1.0  
1040999            604.0  

[1041000 rows x 5 columns]

In [65]:
servis_bakim.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1041000 entries, 0 to 1040999
Data columns (total 5 columns):
Unnamed: 0         1041000 non-null int64
CREATE_DATE        1041000 non-null object
IS_MAINTENANCE     1041000 non-null int64
VEHICLE_ID         1041000 non-null int64
TOTAL_AMOUNT_TL    965596 non-null float64
dtypes: float64(1), int64(3), object(1)
memory usage: 39.7+ MB


In [66]:
servis_bakim.isnull().sum()

Unnamed: 0             0
CREATE_DATE            0
IS_MAINTENANCE         0
VEHICLE_ID             0
TOTAL_AMOUNT_TL    75404
dtype: int64

## Eşsizlik

In [67]:
pd.unique(servis_bakim['IS_MAINTENANCE'])

array([1, 0], dtype=int64)

In [85]:
pd.unique(servis_bakim['TOTAL_AMOUNT_TL'])

array([  192.,   267.,  1747., ..., 26786.,  8770., 14466.])

In [86]:
pd.unique(servis_bakim['TOTAL_AMOUNT_GROUP'])

[1, 6, 2, 4, NaN, ..., 18, 17, 12, 15, 20]
Length: 21
Categories (20, int64): [1 < 2 < 3 < 4 ... 17 < 18 < 19 < 20]

## Values

In [70]:
servis_bakim['IS_MAINTENANCE'].value_counts(dropna=True)

0    558850
1    482150
Name: IS_MAINTENANCE, dtype: int64

In [71]:
servis_bakim['TOTAL_AMOUNT_TL'].value_counts(dropna=True)

1.0        19439
0.0        14857
2.0         3855
30.0        2908
91.0        2742
           ...  
15378.0        1
61521.0        1
15383.0        1
14072.0        1
16051.0        1
Name: TOTAL_AMOUNT_TL, Length: 16006, dtype: int64

In [88]:
servis_bakim['TOTAL_AMOUNT_GROUP'].value_counts()

1     294597
2     254252
3     131327
4      68383
5      39793
6      25952
7      19179
8      14008
9      11031
10      9104
11      7561
12      6245
13      5228
14      4265
15      3495
16      3059
17      2644
18      2162
19      2100
20      1828
Name: TOTAL_AMOUNT_GROUP, dtype: int64

## Column Categorization

- TOTAL_AMOUNT_TL

In [73]:
servis_bakim['TOTAL_AMOUNT_TL'] = servis_bakim['TOTAL_AMOUNT_TL'].astype('str')
cleanup_nums_servis = {"TOTAL_AMOUNT_TL":     {"0.0": np.nan, "1.0": np.nan, "2.0": np.nan}}
servis_bakim = servis_bakim.replace(cleanup_nums_servis)

In [74]:
servis_bakim

Unnamed: 0          CREATE_DATE  IS_MAINTENANCE  VEHICLE_ID  \
0                 0  2010-12-29 10:50:56               1     5000001   
1                 1  2013-08-21 10:34:21               1     5000001   
2                 2  2015-11-30 10:55:00               1     5000001   
3                 3  2015-12-09 13:38:49               0     5000001   
4                 4  2017-11-23 09:53:22               1     5000001   
...             ...                  ...             ...         ...   
1040995     1040995  2021-05-20 14:58:31               0     5344976   
1040996     1040996  2021-05-24 09:57:34               0     5344981   
1040997     1040997  2021-05-25 12:44:02               0     5344999   
1040998     1040998  2021-05-27 09:45:00               0     5345037   
1040999     1040999  2021-05-28 13:46:36               0     5345048   

         TOTAL_AMOUNT_TL  
0                  192.0  
1                  267.0  
2                 1747.0  
3                  465.0  
4                  549.0  
...                  ...  
1040995           1180.0  
1040996              NaN  
1040997           3258.0  
1040998              NaN  
1040999            604.0  

[1041000 rows x 5 columns]

In [83]:
servis_bakim['TOTAL_AMOUNT_GROUP'] = pd.cut(servis_bakim['TOTAL_AMOUNT_TL'], bins=[0,300,600,900,1200,1500,1800,2100,2400,2700,3000,3300,3600,3900,4200,4500,4800,5100,5400,5700,6000], labels=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])

In [84]:
servis_bakim

Unnamed: 0          CREATE_DATE  IS_MAINTENANCE  VEHICLE_ID  \
0                 0  2010-12-29 10:50:56               1     5000001   
1                 1  2013-08-21 10:34:21               1     5000001   
2                 2  2015-11-30 10:55:00               1     5000001   
3                 3  2015-12-09 13:38:49               0     5000001   
4                 4  2017-11-23 09:53:22               1     5000001   
...             ...                  ...             ...         ...   
1040995     1040995  2021-05-20 14:58:31               0     5344976   
1040996     1040996  2021-05-24 09:57:34               0     5344981   
1040997     1040997  2021-05-25 12:44:02               0     5344999   
1040998     1040998  2021-05-27 09:45:00               0     5345037   
1040999     1040999  2021-05-28 13:46:36               0     5345048   

         TOTAL_AMOUNT_TL TOTAL_AMOUNT_GROUP  
0                  192.0                  1  
1                  267.0                  1  
2                 1747.0                  6  
3                  465.0                  2  
4                  549.0                  2  
...                  ...                ...  
1040995           1180.0                  4  
1040996              NaN                NaN  
1040997           3258.0                 11  
1040998              NaN                NaN  
1040999            604.0                  3  

[1041000 rows x 6 columns]

In [91]:
servis_bakim.to_csv("servis_bakim.csv", index=False)